### ISSUE TITLE
AWS deployment best practices

### ISSUE THREAD

**Issue by regispl** [zalando-incubator/saiki-buku#56]
Not really an issue, more a question - are there any best practices on how to deploy Buku in AWS? What I'm asking about specifically is:

1. **Managing changing broker IDs - how should we manage brokers going down (either as a result of a failure as well as e.g. Kafka upgrades)? Is there a way to make this work with AutoScaling?**
We've had a Kafka broker failure some time ago and the fact that the failed node got replaced by new node with new broker ID caused some mess in ZK data: for some reason 4 brokers were "present", including the one that died and I wasn't able to move partitions "off" the dead one - normally I'd recreate the node with existing broker ID, but in this case I couldn't figure out the correct solution as my attempts to reassign partitions were failing (hanging forever on the partitions owned by dead broker). Should we prevent autoscaling from recreating dead nodes and rely on manual process (but still, how do we set broker id in this case anyway)? 

2. **How are you deploying ZK / Kafka in terms of IP assignment?**
It seems like ZK client in Kafka is caching IPs forever (it's not the Java DNS cache thing, which is a separate issue - there's actually a bug for ZK client reported that causes it; it's fixed in 3.4.7+, but Kafka is still on 3.4.6) Are you using static private IPs (not sure it's doable with Senza, but I think it's doable with VPC in general)? Or maybe Elastic IP is the way to go? Or you bounce Kafka brokers every time you add / remove ZK nodes (yuck! 😞 )?

I'll appreciate any suggestions that will help me make our Kafka deployment "production ready" 😉

**Comment by drummerwolli** [comment]
Hi, @regispl ... i recommend using https://github.com/zalando-incubator/bubuku as a spiritual successor of buku. It's more mature now than buku and we are using it in production as well, additionally to the nakadi guys. your both of your questions get answered by this. bubuku is handling this stuff automatically.

**Comment by regispl** [comment]
Thanks!
